SERVER_TRANSCRIBER_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SERVER_TRANSCRIBER_MODELS_DIR="$SERVER_TRANSCRIBER_DIR/models"

# Feel free to use other models
mkdir "$SERVER_TRANSCRIBER_MODELS_DIR/$MODEL_TRANSCRIBER_AUTHOR"
mkdir "$SERVER_TRANSCRIBER_MODELS_DIR/$MODEL_TRANSCRIBER_AUTHOR/$MODEL_TRANSCRIBER_NAME" && huggingface-cli download "$MODEL_TRANSCRIBER_AUTHOR/$MODEL_TRANSCRIBER_NAME" --local-dir "$SERVER_TRANSCRIBER_MODELS_DIR/$MODEL_TRANSCRIBER_AUTHOR/$MODEL_TRANSCRIBER_NAME" --local-dir-use-symlinks False
